[build]
base = "./"
command = "yarn build"
publish = "dist"
functions = "netlify/functions"
ignore = "git diff --quiet HEAD^ HEAD ./src/course ./src/course-listing"

[build.processing]
skip_processing = true

[build.environment]
NODE_VERSION = "18"
YARN_VERSION = "1.22.19"
NODE_ENV = "production"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = [
  "@aws-sdk/*",
  "firebase-admin",
  "firebase",
  "@netlify/functions"
]

[[redirects]]
from = "/api/*"
to = "/netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/stripe-webhook"
to = "/netlify/functions/stripe-webhook"
status = 200
force = true

[[redirects]]
from = "/check-subscription-status"
to = "/netlify/functions/check-subscription-status"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
