[build]
command = "yarn run build-all"
publish = "dist"
functions = ".netlify/functions"

[build.environment]
NODE_VERSION = "18"
YARN_VERSION = "1.22.19"
NODE_ENV = "production"

[functions]
directory = ".netlify/functions"
node_bundler = "esbuild"
included_files = ["src/course/**/*", "src/course-listing/**/*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/stripe-webhook"
to = "/.netlify/functions/stripe-webhook"
status = 200
force = true

[[redirects]]
from = "/check-subscription-status"
to = "/.netlify/functions/check-subscription-status"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://ghost-studio.netlify.app"
Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Credentials = "true"
Cache-Control = "public, max-age=31536000"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.stripe.com; frame-src 'self' https://js.stripe.com;"
